CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    started_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT jobs_status_check CHECK (
        status IN ('pending', 'running', 'completed', 'failed')
    )
);

CREATE INDEX idx_jobs_status_created ON jobs(status, created_at)
WHERE
    status = 'pending';

ALTER TABLE jobs
ADD COLUMN retry_count INT NOT NULL DEFAULT 0,
ADD COLUMN max_retries INT NOT NULL DEFAULT 3,
ADD COLUMN last_err TEXT,
ADD COLUMN next_run_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW();

DROP INDEX IF EXISTS idx_jobs_status_created_at;

CREATE INDEX idx_jobs_status_next_run_at ON jobs (status, next_run_at);


CREATE TABLE dead_jobs (
    id BIGINT PRIMARY KEY,
    type TEXT NOT NULL,
    payload JSONB NOT NULL,
    last_err TEXT,
    failed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    retry_count INT NOT NULL
);